### ISSUE TITLE
use : var accept = require('attr-accept');     accept()   accept is not a function

### ISSUE THREAD

**Issue by glntlq** [react-dropzone/attr-accept#29] opened 2018-07-15 15:40 UTC
use : var accept = require('attr-accept');     
then:  accept()   
result:  accept is not a function  

solution:   import  accept from 'attr-accept' ????

**Comment by okonet** [comment] 2018-08-29 19:10
I’m not sure what this is about.

**Comment by rkmarks** [comment] 2018-08-29 19:15
perhaps he is talking about the README ? as it shows its use in CommonJS instead of a babel/webpack import?

**Comment by okonet** [comment] 2018-08-29 19:42
Hmm 🤔

Do we need to update it?

**Comment by rkmarks** [comment] 2018-08-29 19:44
Is the module available via CommonJS? if so then it should be fine as is, but if not we should perhaps either fix the README or update the module so it is available via CommonJS

**Comment by okonet** [comment] 2018-09-07 08:09
Yes, https://github.com/okonet/attr-accept/blob/master/webpack.config.js#L6

**Comment by bsonntag** [comment] 2019-01-07 14:34
Reproduction here: https://runkit.com/bsonntag/5c3362f019d6b0001713a107

Adding `.default` to the `require()` call fixes it. Like this:

```js
var accept = require('attr-accept').default;
accept({
    name: 'my file.png',
    type: 'image/png'
}, 'image/*')
```

**Comment by fredrikbergqvist** [comment] 2022-10-18 14:45
attr-accept crashes Vite.js production builds because of this

When trying to upload and using react-dropzone with Vite (production build) I get `accepts is not a function` 

if I change: 
`import accepts from 'attr-accept';`
to
```import A from "attr-accept";
const accepts = A.default ? A.default : A;
```
react-dropzone works as it should.

**Comment by rolandjitsu** [comment] 2024-10-07 20:38
@fredrikbergqvist I believe that issue has been fixed with https://github.com/react-dropzone/react-dropzone/commit/2471dd9c63a5b2ef972931761ff30ade06fae2be.

**Comment by rolandjitsu** [comment] 2024-10-07 20:39
Gonna close this issue as there hasn't been any activity on it in years. If there's further issues, we can open a new one.

**Closed** 2024-10-07 20:39 UTC
